# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - saasappcontinaerdev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://saasappregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_711dd76b1aeb41f2b89df7b990448161 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_15c94748777843d1a0862c6991d227cd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: saasappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_711dd76b1aeb41f2b89df7b990448161 }}/alhaj1986/myweb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'saasappcontinaerdev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c45d1e3d2e56497493beb0b2182a9253 }}
        images: 'saasappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_711dd76b1aeb41f2b89df7b990448161 }}/alhaj1986/myweb:${{ github.sha }}'